package view;

import controller.ControllerEstoqueProdutoUsuario;
import controller.ControllerProduto;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.ModelEstoqueProdutoUsuario;
import model.ModelProduto;
import sistema.Mensagens;
import util.Formatador;

/**
 *
 * @author gustavo
 */
public class ViewProduto extends JFrame {

    private ModelProduto modelProduto = new ModelProduto();
    private ArrayList<ModelProduto> listaModelProdutos = new ArrayList<>();
    private String salvarAlterar = "salvar";
    private final ControllerProduto CONTROLLER_PRODUTO = new ControllerProduto();
    private final ControllerEstoqueProdutoUsuario CONTROLLER_ESTOQUE_PRODUTO_USUARIO = new ControllerEstoqueProdutoUsuario();
    private final Formatador FORMATADOR = new Formatador();

    private ArrayList<ModelEstoqueProdutoUsuario> listaModelEstoqueProdutoUsuarios = new ArrayList<>();
    private final ControllerEstoqueProdutoUsuario controllerEstoqueProdutoUsuario = new ControllerEstoqueProdutoUsuario();

    public ViewProduto() {
        initComponents();
        carregarProdutos();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfDescricao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfValor = new javax.swing.JTextField();
        jbSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProdutos = new javax.swing.JTable();
        jbLimpar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produtos");
        setResizable(false);

        jLabel1.setText("Código");

        jtfCodigo.setEditable(false);
        jtfCodigo.setToolTipText("Não preencher este campo");
        jtfCodigo.setEnabled(false);

        jLabel2.setText("Descrição produto");

        jLabel4.setText("Valor");

        jtfValor.setToolTipText("Zero ou maior");

        jbSalvar.setBackground(new java.awt.Color(0, 153, 102));
        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/salvar.png"))); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jtProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Descrição", "Quantidade", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtProdutos);
        if (jtProdutos.getColumnModel().getColumnCount() > 0) {
            jtProdutos.getColumnModel().getColumn(0).setMinWidth(80);
            jtProdutos.getColumnModel().getColumn(0).setPreferredWidth(80);
            jtProdutos.getColumnModel().getColumn(0).setMaxWidth(80);
            jtProdutos.getColumnModel().getColumn(2).setMinWidth(100);
            jtProdutos.getColumnModel().getColumn(2).setPreferredWidth(100);
            jtProdutos.getColumnModel().getColumn(2).setMaxWidth(100);
            jtProdutos.getColumnModel().getColumn(3).setMinWidth(100);
            jtProdutos.getColumnModel().getColumn(3).setPreferredWidth(100);
            jtProdutos.getColumnModel().getColumn(3).setMaxWidth(100);
        }

        jbLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/limpar.png"))); // NOI18N
        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/apagar.png"))); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/editar.png"))); // NOI18N
        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(72, 72, 72)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfDescricao)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jtfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbAlterar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jbSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(jbSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbLimpar)
                    .addComponent(jbExcluir)
                    .addComponent(jbAlterar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed

        modelProduto.setProDescricao(this.jtfDescricao.getText());
        modelProduto.setProQuantidade(0);
        modelProduto.setProValor(0.0d);
        if (!this.estaVazio(this.jtfValor)) {
            modelProduto.setProValor(FORMATADOR.converterVirgulaParaPonto(this.jtfValor.getText()));
        }

        if (CONTROLLER_PRODUTO.validarProdutoFormController(modelProduto)) {
            if (salvarAlterar.equals("salvar")) {
                if (CONTROLLER_PRODUTO.salvarProdutoController(modelProduto)) {
                    JOptionPane.showMessageDialog(this, Mensagens.getMessage("PRD_SALVO"), Mensagens.getMessage("INFO"), JOptionPane.INFORMATION_MESSAGE);
                    this.carregarProdutos();
                    this.limparCampos();
                } else {
                    JOptionPane.showMessageDialog(this, Mensagens.getMessage("PRD_ERRO_SALVAR"), Mensagens.getMessage("ERRO"), JOptionPane.ERROR_MESSAGE);
                }
            } else if (salvarAlterar.equals("alterar")) {
                if (CONTROLLER_PRODUTO.alterarProdutoController(modelProduto)) {
                    JOptionPane.showMessageDialog(this, Mensagens.getMessage("PRD_ALTERADO"), Mensagens.getMessage("INFO"), JOptionPane.INFORMATION_MESSAGE);
                    this.carregarProdutos();
                    this.limparCampos();
                } else {
                    JOptionPane.showMessageDialog(this, Mensagens.getMessage("PRD_ERRO_ALTERAR"), Mensagens.getMessage("ERRO"), JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    Mensagens.getMessage("DADOS_NAO_PREENCHIDOS"),
                    Mensagens.getMessage("ATENCAO"),
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        salvarAlterar = "alterar";
        int linha = jtProdutos.getSelectedRow();
        if (linha < 0) {
            JOptionPane.showMessageDialog(this, Mensagens.getMessage("NAO_SELECIONADO"), Mensagens.getMessage("INFO"), JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                int codigoProduto = (int) this.jtProdutos.getValueAt(linha, 0);
                modelProduto = CONTROLLER_PRODUTO.getProdutoController(codigoProduto);
                this.jtfCodigo.setText(String.valueOf(modelProduto.getProId()));
                this.jtfDescricao.setText(modelProduto.getProDescricao());
                this.jtfValor.setText(String.valueOf(modelProduto.getProValor()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Código inválido ou nenhum registro selecionado!", Mensagens.getMessage("ERRO"), JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        int linha = jtProdutos.getSelectedRow();
        if (linha < 0) {
            JOptionPane.showMessageDialog(this, Mensagens.getMessage("NAO_SELECIONADO"), Mensagens.getMessage("INFO"), JOptionPane.INFORMATION_MESSAGE);
        } else {
            int codigoProduto = (int) jtProdutos.getValueAt(linha, 0);

            if (!CONTROLLER_ESTOQUE_PRODUTO_USUARIO.produtoEstaNoEstoqueController(codigoProduto)) {
                if (CONTROLLER_PRODUTO.excluirProdutoController(codigoProduto)) {
                    JOptionPane.showMessageDialog(this, Mensagens.getMessage("PRD_EXCLUIDO"), Mensagens.getMessage("INFO"), JOptionPane.INFORMATION_MESSAGE);;
                    this.carregarProdutos();
                    limparCampos();
                } else {
                    JOptionPane.showMessageDialog(this, Mensagens.getMessage("PRD_ERRO_EXCLUIR"), Mensagens.getMessage("ERRO"), JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, Mensagens.getMessage("PRD_ERRO_JA_ESTOQUE"), Mensagens.getMessage("ATENCAO"), JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed

        limparCampos();
    }//GEN-LAST:event_jbLimparActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewProduto().setVisible(true);
            }
        });
    }

    private void limparCampos() {
        jtfCodigo.setText("");
        jtfDescricao.setText("");
        jtfValor.setText("0");
        salvarAlterar = "salvar";
    }

    private boolean estaVazio(JTextField pCampoTexto) {
        if (pCampoTexto.getText().isEmpty()) {
            return true;
        }
        return false;
    }

    private void carregarProdutos() {
        listaModelProdutos = CONTROLLER_PRODUTO.getListaProdutoController();
        DefaultTableModel modelo = (DefaultTableModel) jtProdutos.getModel();
        modelo.setNumRows(0);
        int cont = listaModelProdutos.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                listaModelProdutos.get(i).getProId(),
                listaModelProdutos.get(i).getProDescricao(),
                listaModelProdutos.get(i).getProQuantidade(),
                listaModelProdutos.get(i).getProValor()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JTable jtProdutos;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfDescricao;
    private javax.swing.JTextField jtfValor;
    // End of variables declaration//GEN-END:variables
}
